--[[ Exemple :
    antiFreeCam = true  -> Ban and log 
    antiFreeCam = false -> kick and log 
    antiFreeCam = nil   -> disable
]]--


tAD = {}

--#[[ FreeCam ]]#--

tAD.whiteListedCamCoords = {
    {x = 18.09, y = -1121.29, z = 28.91, maxDistance = 10}

}

--#[[ Textures ]]#--

tAD.blackListedTextures = {
    'fm',
    'rampage_tr_main',
    'MenyooExtras',
    'shopui_title_graphics_franklin',
    'deadline',
    'mpleaderboard',
    'digitaloverlay',
    'mpmissmarkers256',
    'elicopterhud',
    'deadline',
    'rampage_tr_main', 
    'mpleaderboard',   
    'cross',
    'mpinventory',   
    'mpmissionend',
    'mpsrange',  
    'trafficcam',
    'mpweaponscommon',   
    'visualflow',
    'mptattoos',   
    'mpweaponsgang1',
    'mphud',   
    'mpweaponsunusedfornow',
    'digitaloverlay',
    'setMenuProperty',
    'bobylebg',
    'mpmissmarkers256',
    'titleBackgroundSprite.dict',
    'titleBackgroundSprite',
    'meow',
    'meow2',  
    'shopui_title_graphics_franklin',
    'gradient_nav',
    'rk36Zr2W8ONhMfo7UavTQ.dict',
    'rk36Zr2W8ONhMfo7UavTQ.text',
    'leaderboard_car_colour_bg',
    'gradient_bgd',
    'titleBackgroundSprite.name',
    'textureDict',
    'textureName',
    'txtRatio',
    'screenX',
    'screenY',
    'heisthud',
    'main_gradient',
    'interaction_bgd',
    'leaderboard_players_icon',
    'mparrow',
    'mp_alerttriangle',
    'pilotschool',
    'hudarrow',
    'arrowright',
    'JTD.dict',
    'JTD.text',
    'arrowleft',
    '0xE7FFAE5EBF23D890',
    'ISMMENU',
    'ISMMENUHeader',
    'ISMMENULogo',
    'shop_box_tick',
    'shop_box_blank',
    'corona_shade',
    'timerbar_sr',
    'timer_cross',
    'timer_tick',
    'header',
    'subTitlebackground',
    'bottomsubTitlebackground',
    'subTitleText',
    'self_pedchanger',
    'veh_nextsprite',
    'wep_ped',
    'srange_gen',
    'hit_cross',
    '0xE7FFAE5EBF23D890',
    'Invoke',
    'cock_moscow',
    'menu_gif',
    'hud_lock',
    'hud_corner',
    'cockmenuuu',
    'loadhack',
    'mpentry',
    'mp_modenotselected_gradient',
    'shared',
    'menuarrow_32',
    'mp_modeselected_gradient',
    '__REAPER2__',
    '__REAPER3__',
    '__REAPER8__',
    '__REAPER10__',
    '__REAPER6__',
    '__REAPER7__',
    '__REAPER5__',
    'lhs_bg',
    '__REAPER23__',
    '__REAPER24__',
    '__REAPER16__',
    '__REAPER15__',
    'mprankbadge',
    'globe_bg',
    '__REAPER21__',
    '__REAPER22__',
    '__REAPER20__',
    '__REAPER19__',
    '__REAPER18__',
    '__REAPER17__',
    '__REAPER14__',
    '__REAPER13__',
    '__REAPER12__',
    '__REAPER11__',
    '__REAPER9__',
    '__REAPER4__',
    '__REAPER1__',
    'combat_htype',
    '0xE7FFAE5EBF23D890',
    'Invoke',
    'DrawSprite',
    '~g~CockMenu',
    'width',
    'cock_moscow',
    'vertissotraperdamnshit',
    'srange_gen',
    'hit_cross',
    'mpentry',
    'mp_modenotselected_gradient',
    'corona_shade',
    'aim-fov-draw-alpha',
    'mpinvperscommon',
    '__PAPYMENU1__',
    '__PAPYMENU2__',
    '__PAPYMENU3__',
    '__PAPYMENU4__',
    '__PAPYMENU5__',
    '__PAPYMENU6__',
    '__PAPYMENU7__',
    '__PAPYMENU8__',
    '__PAPYMENU9__',
    '__PAPYMENU10__',
    '__PAPYMENU11__',
    '__PAPYMENU12__',
    '__PAPYMENU13__',
    '__PAPYMENU14__',
    '__PAPYMENU15__',
    '__PAPYMENU16__',
    '__PAPYMENU17__',
    '__PAPYMENU18__',
    '__PAPYMENU19__',
    '__PAPYMENU20__',
    '__PAPYMENU21__',
    '__PAPYMENU22__',
    '__PAPYMENU23__',
    '__PAPYMENU22__',
    'wmlua.V.AllDraw',
    'shop_tick_icon',
    'mpinventory',
    'mp_specitem_ped',
    'circle_checkpoints',
    'circle_checkpoints_big',
    'basejumping',
    'ped0',
    '1',
    'ped4',
    'ped3',
    'ped2',
    'ped1',
    '2',
    '3',
    '4',
    'arrow_pointer',
    'checkon',
    'titleBackgroundSprite',
    'lagserveur',
    'Fallout',
    'Fivex',
    'Cobra',
}

--#[[ Trigger ]]#--

tAD.triggerProtection = {
    {event = 'LasVegas:RevivePlayer', stopEulen = true, allowed = {
        ['LasVegas'] = true,
    }},
    {event = 'LasVegasesx:setJob', stopEulen = true, allowed = {
    }},
    {event = 'KiLaF:boutique:requestedData', stopEulen = true, allowed = {
    }},
    {event = 'KiLaF:boutique:setVip', stopEulen = true, allowed = {
    }},
    {event = 'LasVegasesx:spawnVehicle', stopEulen = true, allowed = {
    }},

}

tAD.antiBlackListedTrigger = {
   "redst0nia:checking",
  --"gcPhone:_internalAddMessage",
  --"gcPhone:tchat_channel",
  --"esx_vehicleshop:setVehicleOwned",
  "esx_mafiajob:confiscatePlayerItem",
  --"lscustoms:payGarage",
  "vrp_slotmachine:server:2",
  --"Banca:deposit",
  --"bank:deposit",
  --"esx_jobs:caution",
  "give_back",
  "esx_fueldelivery:pay",
  --"esx_carthief:pay",
  "esx_godirtyjob:pay",
  "esx_pizza:pay",
  "esx_ranger:pay",
  "esx_garbagejob:pay",
  "esx_truckerjob:pay",
  "AdminMenu:giveBank",
  "AdminMenu:giveCash",
  "esx_gopostaljob:pay",
  "esx_banksecurity:pay",
  "esx_slotmachine:sv:2",
  --"esx:giveInventoryItem",
  "NB:recruterplayer",
  --"esx_billing:sendBill",
  "esx_jailer:sendToJail",
  "esx_jail:sendToJail",
  "js:jailuser",
  "esx-qalle-jail:jailPlayer",
  --"esx_dmvschool:pay", 
  --"OG_cuffs:cuffCheckNearest",
  --"CheckHandcuff",
  --"cuffServer",
  --"cuffGranted",
  --"police:cuffGranted",
  --"esx_handcuffs:cuffing",
  --"esx_policejob:handcuff",
  --"bank:withdraw",
  --"dmv:success",
  --"esx_skin:responseSaveSkin",
  --"esx_dmvschool:addLicense",
  --"esx_mechanicjob:startCraft",
  "esx_drugs:startHarvestWeed",
  "esx_drugs:startTransformWeed",
  "esx_drugs:startSellWeed",
  "esx_drugs:startHarvestCoke",
  "esx_drugs:startTransformCoke",
  "esx_drugs:startSellCoke",
  "esx_drugs:startHarvestMeth",
  "esx_drugs:startTransformMeth",
  "esx_drugs:startSellMeth",
  "esx_drugs:startHarvestOpium",
  "esx_drugs:startSellOpium",
  "esx_drugs:startTransformOpium",
  "esx_blanchisseur:startWhitening",
  "esx_drugs:stopHarvestCoke",
  "esx_drugs:stopTransformCoke",
  "esx_drugs:stopSellCoke",
  "esx_drugs:stopHarvestMeth",
  "esx_drugs:stopTransformMeth",
  "esx_drugs:stopSellMeth",
  "esx_drugs:stopHarvestWeed",
  "esx_drugs:stopTransformWeed",
  "esx_drugs:stopSellWeed",
  "esx_drugs:stopHarvestOpium",
  "esx_drugs:stopTransformOpium",
  "esx_drugs:stopSellOpium",
  --"esx_society:openBossMenu",
  --"esx_jobs:caution",
  "esx_tankerjob:pay",
  "esx_vehicletrunk:giveDirty",
  "gambling:spend",
  "AdminMenu:giveDirtyMoney",
  --"esx_moneywash:deposit",
  --"esx_moneywash:withdraw",
  "mission:completed",
  "truckerJob:success",
  "99kr-burglary:addMoney",
  "esx_jailer:unjailTime",
  --"esx_ambulancejob:revive",
  --"DiscordBot:playerDied",
  "hentailover:xdlol",
  "antilynx8:anticheat",
  "antilynxr6:detection",
  --"esx:getSharedObject",
  --"esx_society:getOnlinePlayers",
  --"_chat:messageEntered",
  "antilynx8r4a:anticheat",
  "antilynxr4:detect",
  "js:jailuser", 
  "ynx8:anticheat",
  "lynx8:anticheat",
  "adminmenu:allowall",
  "h:xd",
  "ljail:jailplayer",
  "adminmenu:setsalary",
  "adminmenu:cashoutall",
  --"bank:transfer",
  "paycheck:bonus",
  --"paycheck:salary",
  "HCheat:TempDisableDetection",
  "esx_drugs:pickedUpCannabis",
  "esx_drugs:processCannabis",
  "esx-qalle-hunting:reward",
  "esx-qalle-hunting:sell",
  --"esx_mecanojob:onNPCJobCompleted",
  "BsCuff:Cuff696999",
  "veh_SR:CheckMoneyForVeh",
  --"esx_carthief:alertcops",
  "mellotrainer:adminTempBan",
  "mellotrainer:adminKick",
  --"esx_society:putVehicleInGarage"
}

--#[[ Screen ]]#--

tAD.blackListedScreenWords = {
    'fallout', 'Medusa', 'Super Jump', 'fivex', 'godmode', 'server troll', 'modmenu', 'aimbot', 'spectate', 'cheat', 'lua menu', 'falcon', 'kick player', 'trigger', 'give money',
    'give weapon', 'destroy menu', 'weapon menu', 'explode player', 'give armor', 'semi godmode', 'freeze player', 'kick from vehicle', 'magneto', 'attach ufo',
    'attack building', 'online players options', 'esx money', 'esx boss', 'hydro', 'kill engine', 'kick out of veh', 'aimbo1t', 'kill everyone', 'super jump',
    'free cam', 'object spooner', 'injected at', 'misc options', 'world options', 'teleport options', 'vehicle options', 'self options', 'weapon options',
    'esp', 'gamertag', 'repair vehicle', 'customise vehicle', 'power multiplier', 'torque multiplier', 'semi godmode', 'night vision', 'thermal vision',
    'no ragdoll', 'weapon list', 'get all weapons', 'remove weapon', 'no reload', 'no recoil', 'trigger bot', 'rapid fire', 'force mode', 
    'explosive ammo', 'make all vehicles fly', 'dump', 'lua executor', 'carry everyone', 'spam chat', 'fake message', 'fuck server', 'particle effects', 'freeze server',
    'ism', 'ism menu'
}